# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pap.ui'
#
# Created: Thu Oct  6 18:31:19 2016
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(989, 694)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.lineEdit = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(10, 40, 151, 27))
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.lineEdit_2 = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(10, 314, 111, 27))
        self.lineEdit_2.setReadOnly(True)
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.lineEdit_3 = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(10, 10, 521, 27))
        self.lineEdit_3.setReadOnly(True)
        self.lineEdit_3.setObjectName(_fromUtf8("lineEdit_3"))
        self.lineEdit_4 = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_4.setGeometry(QtCore.QRect(10, 344, 111, 27))
        self.lineEdit_4.setReadOnly(True)
        self.lineEdit_4.setObjectName(_fromUtf8("lineEdit_4"))
        self.lineEdit_5 = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_5.setGeometry(QtCore.QRect(10, 284, 521, 27))
        self.lineEdit_5.setReadOnly(True)
        self.lineEdit_5.setObjectName(_fromUtf8("lineEdit_5"))
        self.lineEdit_6 = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_6.setGeometry(QtCore.QRect(170, 40, 113, 27))
        self.lineEdit_6.setObjectName(_fromUtf8("lineEdit_6"))
        self.lineEdit_7 = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_7.setGeometry(QtCore.QRect(10, 100, 151, 27))
        self.lineEdit_7.setReadOnly(True)
        self.lineEdit_7.setObjectName(_fromUtf8("lineEdit_7"))
        self.lineEdit_8 = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_8.setGeometry(QtCore.QRect(10, 130, 151, 27))
        self.lineEdit_8.setReadOnly(True)
        self.lineEdit_8.setObjectName(_fromUtf8("lineEdit_8"))
        self.lineEdit_9 = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_9.setGeometry(QtCore.QRect(170, 100, 251, 27))
        self.lineEdit_9.setObjectName(_fromUtf8("lineEdit_9"))
        self.lineEdit_10 = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_10.setGeometry(QtCore.QRect(170, 130, 251, 27))
        self.lineEdit_10.setObjectName(_fromUtf8("lineEdit_10"))
        self.lineEdit_11 = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_11.setGeometry(QtCore.QRect(10, 374, 111, 27))
        self.lineEdit_11.setReadOnly(True)
        self.lineEdit_11.setObjectName(_fromUtf8("lineEdit_11"))
        self.lineEdit_12 = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_12.setGeometry(QtCore.QRect(10, 404, 111, 27))
        self.lineEdit_12.setReadOnly(True)
        self.lineEdit_12.setObjectName(_fromUtf8("lineEdit_12"))
        self.lineEdit_13 = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_13.setGeometry(QtCore.QRect(167, 314, 113, 27))
        self.lineEdit_13.setObjectName(_fromUtf8("lineEdit_13"))
        self.lineEdit_14 = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_14.setGeometry(QtCore.QRect(167, 344, 113, 27))
        self.lineEdit_14.setObjectName(_fromUtf8("lineEdit_14"))
        self.lineEdit_15 = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_15.setGeometry(QtCore.QRect(167, 374, 113, 27))
        self.lineEdit_15.setObjectName(_fromUtf8("lineEdit_15"))
        self.lineEdit_16 = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_16.setGeometry(QtCore.QRect(167, 405, 113, 27))
        self.lineEdit_16.setObjectName(_fromUtf8("lineEdit_16"))
        self.lineEdit_17 = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_17.setGeometry(QtCore.QRect(10, 434, 113, 27))
        self.lineEdit_17.setReadOnly(True)
        self.lineEdit_17.setObjectName(_fromUtf8("lineEdit_17"))
        self.lineEdit_18 = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_18.setGeometry(QtCore.QRect(167, 434, 111, 27))
        self.lineEdit_18.setText(_fromUtf8(""))
        self.lineEdit_18.setObjectName(_fromUtf8("lineEdit_18"))
        self.lineEdit_19 = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_19.setGeometry(QtCore.QRect(10, 160, 151, 27))
        self.lineEdit_19.setReadOnly(True)
        self.lineEdit_19.setObjectName(_fromUtf8("lineEdit_19"))
        self.lineEdit_20 = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_20.setGeometry(QtCore.QRect(170, 160, 251, 27))
        self.lineEdit_20.setObjectName(_fromUtf8("lineEdit_20"))
        self.lineEdit_21 = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_21.setGeometry(QtCore.QRect(10, 465, 521, 27))
        self.lineEdit_21.setReadOnly(True)
        self.lineEdit_21.setObjectName(_fromUtf8("lineEdit_21"))
        self.pushButton = QtGui.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(430, 160, 98, 27))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.pushButton_2 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(300, 430, 101, 27))
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.lineEdit_22 = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_22.setGeometry(QtCore.QRect(10, 495, 113, 27))
        self.lineEdit_22.setReadOnly(True)
        self.lineEdit_22.setObjectName(_fromUtf8("lineEdit_22"))
        self.lineEdit_23 = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_23.setGeometry(QtCore.QRect(166, 495, 113, 27))
        self.lineEdit_23.setText(_fromUtf8(""))
        self.lineEdit_23.setObjectName(_fromUtf8("lineEdit_23"))
        self.pushButton_3 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(300, 495, 98, 27))
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.lineEdit_24 = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_24.setGeometry(QtCore.QRect(10, 525, 113, 27))
        self.lineEdit_24.setReadOnly(True)
        self.lineEdit_24.setObjectName(_fromUtf8("lineEdit_24"))
        self.lineEdit_25 = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_25.setGeometry(QtCore.QRect(166, 525, 113, 27))
        self.lineEdit_25.setText(_fromUtf8(""))
        self.lineEdit_25.setObjectName(_fromUtf8("lineEdit_25"))
        self.pushButton_4 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(300, 525, 98, 27))
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.pushButton_5 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(10, 620, 521, 27))
        self.pushButton_5.setObjectName(_fromUtf8("pushButton_5"))
        self.lineEdit_26 = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_26.setGeometry(QtCore.QRect(10, 188, 151, 27))
        self.lineEdit_26.setReadOnly(True)
        self.lineEdit_26.setObjectName(_fromUtf8("lineEdit_26"))
        self.checkBox = QtGui.QCheckBox(self.centralwidget)
        self.checkBox.setGeometry(QtCore.QRect(170, 191, 61, 22))
        self.checkBox.setChecked(True)
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.checkBox_2 = QtGui.QCheckBox(self.centralwidget)
        self.checkBox_2.setGeometry(QtCore.QRect(230, 191, 61, 22))
        self.checkBox_2.setChecked(True)
        self.checkBox_2.setObjectName(_fromUtf8("checkBox_2"))
        self.checkBox_3 = QtGui.QCheckBox(self.centralwidget)
        self.checkBox_3.setGeometry(QtCore.QRect(290, 191, 101, 22))
        self.checkBox_3.setChecked(True)
        self.checkBox_3.setObjectName(_fromUtf8("checkBox_3"))
        self.pushButton_6 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(300, 555, 98, 27))
        self.pushButton_6.setObjectName(_fromUtf8("pushButton_6"))
        self.lineEdit_27 = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_27.setGeometry(QtCore.QRect(10, 555, 113, 27))
        self.lineEdit_27.setReadOnly(True)
        self.lineEdit_27.setObjectName(_fromUtf8("lineEdit_27"))
        self.lineEdit_28 = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_28.setGeometry(QtCore.QRect(166, 555, 113, 27))
        self.lineEdit_28.setText(_fromUtf8(""))
        self.lineEdit_28.setObjectName(_fromUtf8("lineEdit_28"))
        self.pushButton_7 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_7.setGeometry(QtCore.QRect(820, 620, 98, 27))
        self.pushButton_7.setObjectName(_fromUtf8("pushButton_7"))
        self.pushButton_8 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_8.setGeometry(QtCore.QRect(720, 620, 98, 27))
        self.pushButton_8.setObjectName(_fromUtf8("pushButton_8"))
        self.textEdit = QtGui.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(540, 40, 371, 571))
        self.textEdit.setObjectName(_fromUtf8("textEdit"))
        self.lineEdit_29 = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_29.setGeometry(QtCore.QRect(540, 10, 371, 27))
        self.lineEdit_29.setReadOnly(True)
        self.lineEdit_29.setObjectName(_fromUtf8("lineEdit_29"))
        self.lineEdit_30 = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_30.setGeometry(QtCore.QRect(10, 70, 151, 27))
        self.lineEdit_30.setReadOnly(True)
        self.lineEdit_30.setObjectName(_fromUtf8("lineEdit_30"))
        self.lineEdit_31 = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_31.setGeometry(QtCore.QRect(170, 70, 113, 27))
        self.lineEdit_31.setObjectName(_fromUtf8("lineEdit_31"))
        self.lineEdit_32 = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_32.setGeometry(QtCore.QRect(10, 585, 113, 27))
        self.lineEdit_32.setReadOnly(True)
        self.lineEdit_32.setObjectName(_fromUtf8("lineEdit_32"))
        self.lineEdit_33 = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_33.setGeometry(QtCore.QRect(166, 586, 113, 27))
        self.lineEdit_33.setText(_fromUtf8(""))
        self.lineEdit_33.setObjectName(_fromUtf8("lineEdit_33"))
        self.pushButton_9 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_9.setGeometry(QtCore.QRect(300, 585, 98, 27))
        self.pushButton_9.setObjectName(_fromUtf8("pushButton_9"))
        self.lineEdit_34 = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_34.setGeometry(QtCore.QRect(10, 220, 151, 27))
        self.lineEdit_34.setReadOnly(True)
        self.lineEdit_34.setObjectName(_fromUtf8("lineEdit_34"))
        self.checkBox_4 = QtGui.QCheckBox(self.centralwidget)
        self.checkBox_4.setGeometry(QtCore.QRect(170, 223, 97, 22))
        self.checkBox_4.setObjectName(_fromUtf8("checkBox_4"))
        self.lineEdit_35 = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_35.setGeometry(QtCore.QRect(10, 252, 151, 27))
        self.lineEdit_35.setReadOnly(True)
        self.lineEdit_35.setObjectName(_fromUtf8("lineEdit_35"))
        self.checkBox_5 = QtGui.QCheckBox(self.centralwidget)
        self.checkBox_5.setGeometry(QtCore.QRect(170, 254, 97, 22))
        self.checkBox_5.setChecked(True)
        self.checkBox_5.setObjectName(_fromUtf8("checkBox_5"))
        self.pushButton_12 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_12.setGeometry(QtCore.QRect(416, 495, 111, 27))
        self.pushButton_12.setObjectName(_fromUtf8("pushButton_12"))
        self.pushButton_13 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_13.setGeometry(QtCore.QRect(416, 525, 111, 27))
        self.pushButton_13.setObjectName(_fromUtf8("pushButton_13"))
        self.pushButton_14 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_14.setGeometry(QtCore.QRect(416, 556, 111, 27))
        self.pushButton_14.setObjectName(_fromUtf8("pushButton_14"))
        self.pushButton_15 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_15.setGeometry(QtCore.QRect(610, 620, 98, 27))
        self.pushButton_15.setObjectName(_fromUtf8("pushButton_15"))
        self.pushButton_16 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_16.setGeometry(QtCore.QRect(420, 430, 111, 27))
        self.pushButton_16.setObjectName(_fromUtf8("pushButton_16"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 989, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "TnSuite", None))
        self.lineEdit.setText(_translate("MainWindow", "K-mer Size", None))
        self.lineEdit_2.setText(_translate("MainWindow", "Match", None))
        self.lineEdit_3.setText(_translate("MainWindow", "Assembly Options", None))
        self.lineEdit_4.setText(_translate("MainWindow", "Mismatch", None))
        self.lineEdit_5.setText(_translate("MainWindow", "Alignment Options ( Smith-Waterman)", None))
        self.lineEdit_6.setText(_translate("MainWindow", "63", None))
        self.lineEdit_7.setText(_translate("MainWindow", "Source sequence", None))
        self.lineEdit_8.setText(_translate("MainWindow", "Sink sequence", None))
        self.lineEdit_11.setText(_translate("MainWindow", "Gap open", None))
        self.lineEdit_12.setText(_translate("MainWindow", "Gap extension", None))
        self.lineEdit_13.setText(_translate("MainWindow", "1", None))
        self.lineEdit_14.setText(_translate("MainWindow", "3", None))
        self.lineEdit_15.setText(_translate("MainWindow", "5", None))
        self.lineEdit_16.setText(_translate("MainWindow", "3", None))
        self.lineEdit_17.setText(_translate("MainWindow", "Reference path", None))
        self.lineEdit_19.setText(_translate("MainWindow", "Raw NGS path", None))
        self.lineEdit_21.setText(_translate("MainWindow", "General Options", None))
        self.pushButton.setText(_translate("MainWindow", "Browse...", None))
        self.pushButton_2.setText(_translate("MainWindow", "Browse...", None))
        self.lineEdit_22.setText(_translate("MainWindow", "Sorting Config", None))
        self.pushButton_3.setText(_translate("MainWindow", "Browse...", None))
        self.lineEdit_24.setText(_translate("MainWindow", "Sample info", None))
        self.pushButton_4.setText(_translate("MainWindow", "Browse...", None))
        self.pushButton_5.setText(_translate("MainWindow", "Configure !!!!!", None))
        self.lineEdit_26.setText(_translate("MainWindow", "Step selection", None))
        self.checkBox.setText(_translate("MainWindow", "sort", None))
        self.checkBox_2.setText(_translate("MainWindow", "trim", None))
        self.checkBox_3.setText(_translate("MainWindow", "assembly", None))
        self.pushButton_6.setText(_translate("MainWindow", "Browse...", None))
        self.lineEdit_27.setText(_translate("MainWindow", "BED file", None))
        self.pushButton_7.setText(_translate("MainWindow", "Run", None))
        self.pushButton_8.setText(_translate("MainWindow", "Quit", None))
        self.lineEdit_29.setText(_translate("MainWindow", "Program CMD information below", None))
        self.lineEdit_30.setText(_translate("MainWindow", "Min k-mer occ", None))
        self.lineEdit_31.setText(_translate("MainWindow", "3", None))
        self.lineEdit_32.setText(_translate("MainWindow", "Output path", None))
        self.pushButton_9.setText(_translate("MainWindow", "Browse...", None))
        self.lineEdit_34.setText(_translate("MainWindow", "Analysis By Sample", None))
        self.checkBox_4.setText(_translate("MainWindow", "Yes", None))
        self.lineEdit_35.setText(_translate("MainWindow", "Downstream Analysis", None))
        self.checkBox_5.setText(_translate("MainWindow", "Yes", None))
        self.pushButton_12.setText(_translate("MainWindow", "Format Ex", None))
        self.pushButton_13.setText(_translate("MainWindow", "Format Ex", None))
        self.pushButton_14.setText(_translate("MainWindow", "Format Ex", None))
        self.pushButton_15.setText(_translate("MainWindow", "Abort", None))
        self.pushButton_16.setText(_translate("MainWindow", "Format Ex", None))

