# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'popup_options.ui'
#
# Created: Fri Apr 28 16:17:11 2017
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(636, 468)
        self.lineEdit = QtGui.QLineEdit(Form)
        self.lineEdit.setGeometry(QtCore.QRect(10, 10, 611, 27))
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.lineEdit_2 = QtGui.QLineEdit(Form)
        self.lineEdit_2.setGeometry(QtCore.QRect(10, 40, 191, 27))
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.lineEdit_3 = QtGui.QLineEdit(Form)
        self.lineEdit_3.setGeometry(QtCore.QRect(210, 40, 113, 27))
        self.lineEdit_3.setObjectName(_fromUtf8("lineEdit_3"))
        self.lineEdit_4 = QtGui.QLineEdit(Form)
        self.lineEdit_4.setGeometry(QtCore.QRect(10, 70, 191, 27))
        self.lineEdit_4.setObjectName(_fromUtf8("lineEdit_4"))
        self.lineEdit_5 = QtGui.QLineEdit(Form)
        self.lineEdit_5.setGeometry(QtCore.QRect(210, 70, 113, 27))
        self.lineEdit_5.setObjectName(_fromUtf8("lineEdit_5"))
        self.lineEdit_6 = QtGui.QLineEdit(Form)
        self.lineEdit_6.setGeometry(QtCore.QRect(10, 100, 191, 27))
        self.lineEdit_6.setObjectName(_fromUtf8("lineEdit_6"))
        self.pushButton = QtGui.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(520, 40, 98, 27))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.pushButton_2 = QtGui.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(520, 70, 98, 27))
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.checkBox = QtGui.QCheckBox(Form)
        self.checkBox.setGeometry(QtCore.QRect(211, 102, 61, 22))
        self.checkBox.setChecked(True)
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.checkBox_2 = QtGui.QCheckBox(Form)
        self.checkBox_2.setGeometry(QtCore.QRect(271, 102, 61, 22))
        self.checkBox_2.setChecked(True)
        self.checkBox_2.setObjectName(_fromUtf8("checkBox_2"))
        self.checkBox_3 = QtGui.QCheckBox(Form)
        self.checkBox_3.setGeometry(QtCore.QRect(331, 102, 91, 22))
        self.checkBox_3.setChecked(True)
        self.checkBox_3.setObjectName(_fromUtf8("checkBox_3"))
        self.checkBox_4 = QtGui.QCheckBox(Form)
        self.checkBox_4.setGeometry(QtCore.QRect(422, 103, 97, 22))
        self.checkBox_4.setChecked(True)
        self.checkBox_4.setObjectName(_fromUtf8("checkBox_4"))
        self.pushButton_3 = QtGui.QPushButton(Form)
        self.pushButton_3.setGeometry(QtCore.QRect(520, 100, 98, 27))
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.lineEdit_7 = QtGui.QLineEdit(Form)
        self.lineEdit_7.setGeometry(QtCore.QRect(10, 282, 611, 27))
        self.lineEdit_7.setObjectName(_fromUtf8("lineEdit_7"))
        self.lineEdit_8 = QtGui.QLineEdit(Form)
        self.lineEdit_8.setGeometry(QtCore.QRect(10, 312, 191, 27))
        self.lineEdit_8.setObjectName(_fromUtf8("lineEdit_8"))
        self.lineEdit_9 = QtGui.QLineEdit(Form)
        self.lineEdit_9.setGeometry(QtCore.QRect(210, 312, 113, 27))
        self.lineEdit_9.setObjectName(_fromUtf8("lineEdit_9"))
        self.lineEdit_10 = QtGui.QLineEdit(Form)
        self.lineEdit_10.setGeometry(QtCore.QRect(10, 342, 191, 27))
        self.lineEdit_10.setObjectName(_fromUtf8("lineEdit_10"))
        self.lineEdit_11 = QtGui.QLineEdit(Form)
        self.lineEdit_11.setGeometry(QtCore.QRect(210, 342, 113, 27))
        self.lineEdit_11.setObjectName(_fromUtf8("lineEdit_11"))
        self.lineEdit_12 = QtGui.QLineEdit(Form)
        self.lineEdit_12.setGeometry(QtCore.QRect(10, 372, 191, 27))
        self.lineEdit_12.setObjectName(_fromUtf8("lineEdit_12"))
        self.lineEdit_13 = QtGui.QLineEdit(Form)
        self.lineEdit_13.setGeometry(QtCore.QRect(210, 372, 113, 27))
        self.lineEdit_13.setObjectName(_fromUtf8("lineEdit_13"))
        self.lineEdit_14 = QtGui.QLineEdit(Form)
        self.lineEdit_14.setGeometry(QtCore.QRect(10, 402, 191, 27))
        self.lineEdit_14.setObjectName(_fromUtf8("lineEdit_14"))
        self.lineEdit_15 = QtGui.QLineEdit(Form)
        self.lineEdit_15.setGeometry(QtCore.QRect(210, 402, 113, 27))
        self.lineEdit_15.setObjectName(_fromUtf8("lineEdit_15"))
        self.lineEdit_16 = QtGui.QLineEdit(Form)
        self.lineEdit_16.setGeometry(QtCore.QRect(10, 130, 191, 27))
        self.lineEdit_16.setObjectName(_fromUtf8("lineEdit_16"))
        self.lineEdit_17 = QtGui.QLineEdit(Form)
        self.lineEdit_17.setGeometry(QtCore.QRect(210, 130, 191, 27))
        self.lineEdit_17.setObjectName(_fromUtf8("lineEdit_17"))
        self.pushButton_4 = QtGui.QPushButton(Form)
        self.pushButton_4.setGeometry(QtCore.QRect(420, 130, 98, 27))
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.pushButton_5 = QtGui.QPushButton(Form)
        self.pushButton_5.setGeometry(QtCore.QRect(520, 130, 98, 27))
        self.pushButton_5.setObjectName(_fromUtf8("pushButton_5"))
        self.pushButton_6 = QtGui.QPushButton(Form)
        self.pushButton_6.setGeometry(QtCore.QRect(520, 310, 98, 27))
        self.pushButton_6.setObjectName(_fromUtf8("pushButton_6"))
        self.pushButton_7 = QtGui.QPushButton(Form)
        self.pushButton_7.setGeometry(QtCore.QRect(520, 339, 98, 27))
        self.pushButton_7.setObjectName(_fromUtf8("pushButton_7"))
        self.pushButton_8 = QtGui.QPushButton(Form)
        self.pushButton_8.setGeometry(QtCore.QRect(520, 370, 98, 27))
        self.pushButton_8.setObjectName(_fromUtf8("pushButton_8"))
        self.pushButton_9 = QtGui.QPushButton(Form)
        self.pushButton_9.setGeometry(QtCore.QRect(520, 400, 98, 27))
        self.pushButton_9.setObjectName(_fromUtf8("pushButton_9"))
        self.pushButton_10 = QtGui.QPushButton(Form)
        self.pushButton_10.setGeometry(QtCore.QRect(327, 440, 291, 27))
        self.pushButton_10.setObjectName(_fromUtf8("pushButton_10"))
        self.pushButton_11 = QtGui.QPushButton(Form)
        self.pushButton_11.setGeometry(QtCore.QRect(10, 440, 311, 27))
        self.pushButton_11.setObjectName(_fromUtf8("pushButton_11"))
        self.lineEdit_18 = QtGui.QLineEdit(Form)
        self.lineEdit_18.setGeometry(QtCore.QRect(10, 160, 191, 27))
        self.lineEdit_18.setObjectName(_fromUtf8("lineEdit_18"))
        self.checkBox_5 = QtGui.QCheckBox(Form)
        self.checkBox_5.setGeometry(QtCore.QRect(210, 163, 97, 22))
        self.checkBox_5.setChecked(True)
        self.checkBox_5.setObjectName(_fromUtf8("checkBox_5"))
        self.lineEdit_19 = QtGui.QLineEdit(Form)
        self.lineEdit_19.setGeometry(QtCore.QRect(10, 190, 191, 27))
        self.lineEdit_19.setObjectName(_fromUtf8("lineEdit_19"))
        self.lineEdit_20 = QtGui.QLineEdit(Form)
        self.lineEdit_20.setGeometry(QtCore.QRect(210, 190, 113, 27))
        self.lineEdit_20.setObjectName(_fromUtf8("lineEdit_20"))
        self.lineEdit_21 = QtGui.QLineEdit(Form)
        self.lineEdit_21.setGeometry(QtCore.QRect(10, 220, 191, 27))
        self.lineEdit_21.setObjectName(_fromUtf8("lineEdit_21"))
        self.checkBox_6 = QtGui.QCheckBox(Form)
        self.checkBox_6.setGeometry(QtCore.QRect(210, 223, 111, 22))
        self.checkBox_6.setObjectName(_fromUtf8("checkBox_6"))
        self.checkBox_7 = QtGui.QCheckBox(Form)
        self.checkBox_7.setGeometry(QtCore.QRect(320, 223, 111, 22))
        self.checkBox_7.setObjectName(_fromUtf8("checkBox_7"))
        self.lineEdit_22 = QtGui.QLineEdit(Form)
        self.lineEdit_22.setGeometry(QtCore.QRect(420, 220, 111, 27))
        self.lineEdit_22.setObjectName(_fromUtf8("lineEdit_22"))
        self.lineEdit_23 = QtGui.QLineEdit(Form)
        self.lineEdit_23.setGeometry(QtCore.QRect(550, 220, 61, 27))
        self.lineEdit_23.setObjectName(_fromUtf8("lineEdit_23"))

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Options", None))
        self.lineEdit.setText(_translate("Form", "Additional de novo assembly options", None))
        self.lineEdit_2.setText(_translate("Form", "k-mer size", None))
        self.lineEdit_3.setText(_translate("Form", "63", None))
        self.lineEdit_4.setText(_translate("Form", "Minimum K-mer occurence", None))
        self.lineEdit_5.setText(_translate("Form", "3", None))
        self.lineEdit_6.setText(_translate("Form", "Analysis Steps", None))
        self.pushButton.setText(_translate("Form", "Description", None))
        self.pushButton_2.setText(_translate("Form", "Description", None))
        self.checkBox.setText(_translate("Form", "Sort", None))
        self.checkBox_2.setText(_translate("Form", "Trim", None))
        self.checkBox_3.setText(_translate("Form", "Assembly", None))
        self.checkBox_4.setText(_translate("Form", "Analysis", None))
        self.pushButton_3.setText(_translate("Form", "Description", None))
        self.lineEdit_7.setText(_translate("Form", "Smith-Waterman alignement options", None))
        self.lineEdit_8.setText(_translate("Form", "Sequence match score", None))
        self.lineEdit_9.setText(_translate("Form", "1", None))
        self.lineEdit_10.setText(_translate("Form", "Sequence mismatch score", None))
        self.lineEdit_11.setText(_translate("Form", "3", None))
        self.lineEdit_12.setText(_translate("Form", "Gap open penalty", None))
        self.lineEdit_13.setText(_translate("Form", "5", None))
        self.lineEdit_14.setText(_translate("Form", "Gap extension penalty", None))
        self.lineEdit_15.setText(_translate("Form", "3", None))
        self.lineEdit_16.setText(_translate("Form", "BED file", None))
        self.pushButton_4.setText(_translate("Form", "Browse...", None))
        self.pushButton_5.setText(_translate("Form", "Description", None))
        self.pushButton_6.setText(_translate("Form", "Description", None))
        self.pushButton_7.setText(_translate("Form", "Description", None))
        self.pushButton_8.setText(_translate("Form", "Description", None))
        self.pushButton_9.setText(_translate("Form", "Description", None))
        self.pushButton_10.setText(_translate("Form", "Save changes", None))
        self.pushButton_11.setText(_translate("Form", "Set default", None))
        self.lineEdit_18.setText(_translate("Form", "Down Sampling", None))
        self.checkBox_5.setText(_translate("Form", "On/Off", None))
        self.lineEdit_19.setText(_translate("Form", "Down sampling ratio", None))
        self.lineEdit_20.setText(_translate("Form", "0.3", None))
        self.lineEdit_21.setText(_translate("Form", "Seed Mismatch Correction", None))
        self.checkBox_6.setText(_translate("Form", "Depth", None))
        self.checkBox_7.setText(_translate("Form", "Mismatch", None))
        self.lineEdit_22.setText(_translate("Form", "Num mismatch", None))
        self.lineEdit_23.setText(_translate("Form", "3", None))

